# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aXGVw5XuD7chofkKk_wzUqNvves_J2Ro
"""

print("Sajad Ali")

print("Artificial Intelligence")  # 2.

print("21")

print(18+24)

#4
print("Sajad Ali")
print("Semester 5")

city ="Kabal"
print("Welcome to ",city)

##Variables 1
name = "Sajad Ali"
age = 21
city ="Kabal"
print(name)
print(age)
print(city)

#2 variables
marks =70
marks = 85
print(marks)

#3 variables
university = "University Of Swat"
print (university)

#4 variables
length = 10
width = 5
print(length)
print(width)

#5 variable
is_student=True
print(is_student)

#6 variable
a = 5
b = 10
a, b = b,a
print(a)
print(b)

# Basic Data Types
#1
num = 10
dec = 5.5
text = "Hello"
flag = True
print(num)
print(dec)
print(text)
print(flag)

#2
print(type(100))

print(type(10.5))

print(type("100"))  # 4.

print(type("passed"))  # 5.

price = 99.99
print(price)
print(type(price))  # 6.

# Taking Input with input()
name = input("Enter your name: ")
print("Welcome", name)  # 1.

first = input("Enter first name: ")
last = input("Enter last name: ")
print(first, last)  # 3.

language = input("Enter your favorite programming language: ")
print(language)  # 4.

age = input("Enter your age: ")
print(type(age))  # 5.

university = input("Enter university name: ")
semester = input("Enter semester: ")
course = input("Enter course name: ")
print(university, semester, course)  # 6.

#type conversion (Type casting
num1 = int(input("Enter first integer: "))
num2 = int(input("Enter second integer: "))
print(num1 + num2)  # 1.

temperature = float(input("Enter temperature: "))
print(temperature)  # 2.

birth_year = int(input("Enter birth year: "))
age = 2026 - birth_year
print("Approximate age:", age)  # 3.

price = float(input("Enter item price: "))
quantity = int(input("Enter quantity: "))
print("Total price:", price * quantity)  # 4.

number = 500
text = str(number)
print(text)
print(type(text))  # 5.

m1 = int(input("Enter marks 1: "))
m2 = int(input("Enter marks 2: "))
m3 = int(input("Enter marks 3: "))
print("Total:", m1 + m2 + m3)  # 6.

#^6 ARITHMATIC OPERATIONS
a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
print(a + b)
print(a - b)
print(a * b)
print(a / b)  # 1.

print(49 % 6)  # 2.

print(3 ** 4)  # 3.

length = float(input("Enter length: "))
width = float(input("Enter width: "))
print("Area:", length * width)  # 4.

minutes = int(input("Enter number of minutes: "))
hours = minutes // 60
remaining = minutes % 60
print(hours, "hours and", remaining, "minutes")  # 5.

m1 = float(input("Enter marks 1: "))
m2 = float(input("Enter marks 2: "))
m3 = float(input("Enter marks 3: "))
print("Average:", (m1 + m2 + m3) / 3)  # 6.

radius = float(input("Enter radius: "))
area = 3.14159 * radius ** 2
print("Area:", area)  # 7.

#7 COMPARISON OPERATORS
a = 25
b = 30
print(a == b)
print(a != b)
print(a < b)
print(a > b)  # 1.

age = int(input("Enter age: "))
print(age >= 18)  # 2.

n1 = float(input("Enter first number: "))
n2 = float(input("Enter second number: "))
print(n1 == n2)  # 3.

marks = 49
print(marks >= 50)  # 4.

1password = input("Enter password: ")
print(password == "ai2026")  # 5.

temperature = float(input("Enter temperature: "))
print(temperature < 20)  # 6.

h1 = float(input("Enter first height: "))
h2 = float(input("Enter second height: "))
print(h1 > h2)  # 7.

#8 LOGICAL OPERATORS
age = 22
has_id = True
print(age >= 18 and has_id)  # 1.

num = float(input("Enter a number: "))
print(num > 10 and num < 50)  # 2.

day = input("Enter a day: ")
print(day == "Saturday" or day == "Sunday")  # 3.

is_logged_in = False
print(not is_logged_in)  # 4.

marks = float(input("Enter marks: "))
attendance = float(input("Enter attendance: "))
print(marks >= 50 and attendance >= 75)  # 5.

character = input("Enter a character: ")
print(character == "a" or character == "e")  # 6.

x = True
y = False
print(x and y)
print(x or y)
print(not x)  # 7.

#9 Strings
first = "Sajad"
last = "Ali"
print(first + " " + last)  # 1.

word = input("Enter a word: ")
print(len(word))  # 2.

print("Artificial"[0])  # 3.

print("Intelligence"[-1])  # 4.

name = input("Enter your name: ")
print(name.upper())  # 5.

city = input("Enter your city: ")
print(city.capitalize())  # 6.

sentence = "Artificial Intelligence Lab"
print(sentence[3])  # 7.

#10 The IF STATEMENT
age = int(input("Enter age: "))
if age >= 18:
    print("Eligible")  # 1.

marks = int(input("Enter marks: "))
if marks >= 50:
    print("Pass")  # 2.

num = float(input("Enter a number: "))
if num > 0:
    print("Positive")  # 3.

temperature = float(input("Enter temperature: "))
if temperature > 35:
    print("Hot")  # 4.

password = input("Enter password: ")
if password == "python123":
    print("Access granted")  # 5.

attendance = float(input("Enter attendance percentage: "))
if attendance >= 75:
    print("Good attendance")  # 6.

salary = float(input("Enter salary: "))
if salary > 100000:
    print("Tax review required")  # 7.

#11 If else
num = float(input("Enter a number: "))
if num > 0:
    print("Positive")
else:
    print("Not positive")  # 1.

age = int(input("Enter age: "))
if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")  # 2.

marks = int(input("Enter marks: "))
if marks >= 50:
    print("Pass")
else:
    print("Fail")  # 3.

num = int(input("Enter a number: "))
if num % 2 == 0:
    print("Even")
else:
    print("Odd")  # 4.

password = input("Enter password: ")
if password == "python123":
    print("Correct password")
else:
    print("Incorrect password")  # 5.

temperature = float(input("Enter temperature: "))
if temperature > 30:
    print("Hot")
else:
    print("Normal")  # 6.

year = int(input("Enter year: "))
if year % 4 == 0:
    print("Divisible by 4")
else:
    print("Not divisible by 4")  # 7.

#12 if-elif-else
marks = int(input("Enter marks: "))
if marks >= 80:
    print("A")
elif marks >= 70:
    print("B")
elif marks >= 60:
    print("C")
elif marks >= 50:
    print("D")
else:
    print("F")  # 1.

age = int(input("Enter age: "))
if age < 13:
    print("Child")
elif age < 20:
    print("Teenager")
elif age < 60:
    print("Adult")
else:
    print("Senior")  # 2.

num = float(input("Enter a number: "))
if num > 0:
    print("Positive")
elif num < 0:
    print("Negative")
else:
    print("Zero")  # 3.

temperature = float(input("Enter temperature: "))
if temperature < 10:
    print("Cold")
elif temperature < 25:
    print("Mild")
elif temperature < 35:
    print("Warm")
else:
    print("Hot")  # 4.

month = int(input("Enter month number (1-12): "))
if month == 1:
    print("January")
elif month == 2:
    print("February")
elif month == 3:
    print("March")
elif month == 4:
    print("April")
else:
    print("Invalid month")  # 5. (add more elif for remaining months)

choice = int(input("Enter choice (1-3): "))
if choice == 1:
    print("You selected option 1")
elif choice == 2:
    print("You selected option 2")
elif choice == 3:
    print("You selected option 3")
else:
    print("Invalid choice")  # 6.

color = input("Enter traffic light color: ")
if color == "red":
    print("Stop")
elif color == "yellow":
    print("Wait")
elif color == "green":
    print("Go")
else:
    print("Invalid color")  # 7.

#13 Nested If Statement
age = int(input("Enter age: "))
has_id = input("Do you have an ID? (yes/no): ")
if age >= 18:
    if has_id == "yes":
        print("Entry allowed")
    else:
        print("ID required")
else:
    print("Age requirement not met")  # 1.

username = input("Enter username: ")
if username == "admin":
    password = input("Enter password: ")
    if password == "admin123":
        print("Login successful")
    else:
        print("Incorrect password")
else:
    print("Incorrect username")  # 2.

marks = int(input("Enter marks: "))
if marks >= 50:
    attendance = int(input("Enter attendance: "))
    if attendance >= 75:
        print("Course passed")
    else:
        print("Attendance requirement not met")
else:
    print("Marks requirement not met")  # 3.

num = int(input("Enter a number: "))
if num > 0:
    if num % 2 == 0:
        print("Positive and Even")
    else:
        print("Positive and Odd")
else:
    print("Not a positive number")  # 4.

temperature = float(input("Enter temperature: "))
if temperature > 30:
    ac = input("Do you have an air conditioner? (yes/no): ")
    if ac == "yes":
        print("Turn on the AC")
    else:
        print("Stay hydrated, it is hot")
else:
    print("Temperature is comfortable")  # 5.

balance = float(input("Enter account balance: "))
if balance > 0:
    withdrawal = float(input("Enter withdrawal amount: "))
    if withdrawal <= balance:
        print("Withdrawal successful")
    else:
        print("Insufficient balance")
else:
    print("Account balance is zero or negative")  # 6.

#14 While Loop
count = 1
while count <= 10:
    print(count)
    count = count + 1  # 1.

n = 10
while n >= 1:
    print(n)
    n = n - 1  # 2.

n = 2
while n <= 20:
    print(n)
    n = n + 2  # 3.

num = int(input("Enter a number: "))
i = 1
while i <= 10:
    print(num, "x", i, "=", num * i)
    i = i + 1  # 4.

password = ""
while password != "python":
    password = input("Enter password: ")
print("Access granted")  # 5.

total = 0
i = 1
while i <= 100:
    total = total + i
    i = i + 1
print(total)  # 6.

num = int(input("Enter a positive number: "))
while num <= 0:
    num = int(input("Enter a positive number: "))
print("You entered:", num)  # 7.

n = int(input("Enter starting number for countdown: "))
while n >= 0:
    print(n)
    n = n - 1  # 8.

#FOR LOOPS
for i in range(1, 11):
    print(i)  # 1.

for i in range(5):
    print("Sajad Ali")  # 2.

for i in range(5):
    print("Ali Khan")  # 2. replace with your own name

for i in range(10, 21):
    print(i)  # 4.

for i in range(1, 51):
    print(i)  # 5.

num = int(input("Enter a number: "))
for i in range(1, 11):
    print(num, "x", i, "=", num * i)  # 6.

total = 0
for i in range(1, 21):
    total = total + i
print(total)  # 7.

for i in range(1, 11):
    print(i ** 2)  # 8.

#16 range()
for i in range(10):
    print(i)  # 1.

for i in range(5, 16):
    print(i)  # 2.

for i in range(2, 31, 2):
    print(i)  # 3.

for i in range(20, 0, -1):
    print(i)  # 5.

for i in range(5, 51, 5):
    print(i)  # 6.

for i in range(100, 9, -10):
    print(i)  # 7.

# break and continue
for i in range(1, 100):
    if i == 8:
        break
    print(i)  # 1.

for i in range(1, 11):
    if i == 4:
        continue
    print(i)  # 2.

for i in range(1, 21):
    if i % 2 == 0:
        continue
    print(i)  # 3.

while True:
    text = input("Enter text (type stop to end): ")
    if text == "stop":
        break
    print("You entered:", text)  # 4.

for i in range(1, 101):
    if i > 50 and i % 7 == 0:
        print(i)
        break  # 5.

for i in range(1, 31):
    if i % 3 == 0:
        continue
    print(i)  # 6.

while True:
    command = input("Enter command (type exit to stop): ")
    if command == "exit":
        break
    print("Command received:", command)  # 7.

#18 Cobined Lab Challenges
import random

secret = random.randint(1, 100)
guess = int(input("Guess the number (1-100): "))
if guess == secret:
    print("Correct!")
elif guess > secret:
    print("Too high")
else:
    print("Too low")  # 1.

m1 = float(input("Enter marks 1: "))
m2 = float(input("Enter marks 2: "))
m3 = float(input("Enter marks 3: "))
average = (m1 + m2 + m3) / 3
if average >= 80:
    grade = "A"
elif average >= 70:
    grade = "B"
elif average >= 60:
    grade = "C"
elif average >= 50:
    grade = "D"
else:
    grade = "F"
print("Average:", average)
print("Grade:", grade)  # 2.

correct_password = "python123"
attempts = 0
while attempts < 3:
    password = input("Enter password: ")
    if password == correct_password:
        print("Login successful")
        break
    else:
        attempts = attempts + 1
        print("Incorrect password")
else:
    print("Account locked, too many failed attempts")  # 3.

num = int(input("Enter a number: "))
for i in range(1, 11):
    print(num, "x", i, "=", num * i)  # 4.

print("1. Add\n2. Subtract\n3. Multiply\n4. Divide")
choice = int(input("Enter choice (1-4): "))
a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
if choice == 1:
    print(a + b)
elif choice == 2:
    print(a - b)
elif choice == 3:
    print(a * b)
elif choice == 4:
    print(a / b)
else:
    print("Invalid choice")  # 5.

positive = 0
negative = 0
zero = 0
for i in range(10):
    num = float(input("Enter number " + str(i + 1) + ": "))
    if num > 0:
        positive = positive + 1
    elif num < 0:
        negative = negative + 1
    else:
        zero = zero + 1
print("Positive:", positive)
print("Negative:", negative)
print("Zero:", zero)  # 6.

num = int(input("Enter a number: "))
is_prime = True
if num < 2:
    is_prime = False
else:
    for i in range(2, num):
        if num % i == 0:
            is_prime = False
            break
print(is_prime)  # 7.

for i in range(1, 101):
    if i % 3 == 0 and i % 5 == 0:
        print(i)  # 8.

marks = float(input("Enter marks: "))
attendance = float(input("Enter attendance: "))
if marks >= 50 and attendance >= 75:
    print("Pass")
elif marks < 50:
    print("Fail")
else:
    print("Attendance Shortage")  # 9.

likes_programming = input("Do you like programming? (yes/no): ")
likes_math = input("Do you like mathematics? (yes/no): ")
likes_design = input("Do you like design? (yes/no): ")
likes_data = input("Do you like data? (yes/no): ")

if likes_programming == "yes":
    print("Consider Software Engineering")
elif likes_math == "yes":
    print("Consider Data Science / AI")
elif likes_design == "yes":
    print("Consider UI/UX Design")
elif likes_data == "yes":
    print("Consider Data Analytics")
else:
    print("Explore general Computer Science")  # 10.

while True:
    temperature = input("Enter temperature (type exit to stop): ")
    if temperature == "exit":
        break
    temperature = float(temperature)
    if temperature < 10:
        print("Cold")
    elif temperature < 25:
        print("Normal")
    elif temperature < 35:
        print("Warm")
    else:
        print("Hot")  # 11.

print("Note: This is only a programming exercise, not a medical diagnosis.")
symptom1 = input("Symptom 1 (e.g., fever/cough/none): ")
symptom2 = input("Symptom 2: ")
symptom3 = input("Symptom 3: ")

symptoms = [symptom1, symptom2, symptom3]
count = 0
for s in symptoms:
    if s.lower() != "none":
        count = count + 1

if count == 0:
    print("Rest")
elif count <= 2:
    print("Monitor")
else:
    print("Seek Professional Advice")  # 12.